### ISSUE TITLE
Recent gem releases not reflected in Github?

### ISSUE THREAD

**Issue by rdlugosz** [clbustos/statsample#43]
I noticed while upgrading some gems that Statsample went from `1.4.0` to `1.4.2` and [Minimization](https://github.com/clbustos/minimization) went from `0.2.1` to `0.2.2` (_and appears to have created a hard dependency on `rb-gsl`, as my heroku build failed_—which led me here to investigate what changed).

Although I see an updated `History.txt` in both Gems, there's nothing reflected in the Github repos in the way of commits or tags. Were these releases made intentionally? Could we get the changes pushed to master? 

Also, is `rb-gsl` going to become a hard dependency of statsample or minimization? (By locking to 1.4.0 and 0.2.1 I do not have rb-gsl in my dependency tree.)

Thanks!

**Comment by agarie** [comment]
Hi! The currently maintained repository is the [SciRuby fork](https://github.com/sciruby/statsample). There are forks for integration, minimization and distribution as well.

Can you open an issue about the hard dependency? I'll fix it this week. Sorry about that, I probably added it as a dependency by mistake when adding a gemspec.

**Comment by rdlugosz** [comment]
Ah! Thanks. Would it be possible to drop a note in the top of the readme in this repo that points people to the new canonical repo?
